services:
  postgres:
    image: postgres:16
    container_name: binomo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: binomo
    ports:
      - "5434:5432"  # хостовый порт изменен, чтобы избежать конфликта с binomo2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - binomo_network

  backend:
    build: .
    container_name: binomo_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - binomo_network

volumes:
  postgres_data:

networks:
  binomo_network:
    driver: bridge


